# Generated by Django 5.2 on 2025-04-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registermodel',
            table=None,
        ),
    ]
